config/routes.rb
Rails.application.routes.draw do
  resources :brands
  get 'welcome/index'
  resources :cars
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: 'welcome#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :cars, :dependent => :destroy

    validates :brand_name, presence: true, length: 2..28, uniqueness: true
end

app/models/car.rb
class Car < ApplicationRecord
    belongs_to :brand

    validates :description, presence: true, length: 2..60
    validates :year, numericality: true, length: { is: 4 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    if params[:locale]
      cookies[:locale] = params[:locale]
    end
        
    if cookies[:locale]
      if I18n.locale != cookies[:locale]
        I18n.locale = cookies[:locale]
      end  
    end    
  end    
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: %i[ show edit update destroy ]

  # GET /brands or /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1 or /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands or /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to brand_url(@brand), notice: t('notices.brand.create') }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1 or /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to brand_url(@brand), notice: t('notices.brand.update') }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1 or /brands/1.json
  def destroy
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url, notice: t('notices.brand.destroy') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def brand_params
      params.require(:brand).permit(:brand_name)
    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]
  before_action :set_brand_options, only: [:new, :create, :edit, :update]

  # GET /cars or /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to car_url(@car), notice: t('notices.car.create') }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to car_url(@car), notice: t('notices.car.update') }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy

    respond_to do |format|
      format.html { redirect_back_or_to :back, notice: t('notices.car.destroy') }
      format.json { head :no_content }
    end
  end

  private
    def set_brand_options
      @brand_options = Brand.all.pluck(:brand_name, :id)
    end  

    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:description, :year, :url_image, :brand_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def active_link_to(name, path)
        paths = [path, "#{path}/new", "#{path}/#{params[:id]}", "#{path}/#{params[:id]}/edit"]
        content_tag(:li, class: "#{'active font-weight-bold bg-light' if paths.any? { |i| current_page?(i)} } nav-item") do
          link_to name, path, class: "nav-link"
        end
    end  
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
  def car_url_image(car)
     car_image = car.url_image
     !car_image.empty? ? car_image : "default_car.jpg"     
  end  

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/brands/_brand.html.erb
<div id="<%= dom_id brand %>">
  <p>
    <strong>Brand name:</strong>
    <%= brand.brand_name %>
  </p>

</div>

app/views/brands/_form.html.erb
<%= form_with(model: brand, local: true) do |form| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, t('error', count: brand.errors.count)) %> <%= t('error_explanation.brand', count: brand.errors.count) %></h2>

      <ul>
      <% brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :brand_name %>
    <%= form.text_field :brand_name, class:"form-control", placeholder:"Volkswagen" %>
  </div>

  <div class="actions">
    <%= form.submit nil, class:"btn btn-primary" %>
  </div>
<% end %>

</br>

app/views/brands/edit.html.erb
<h1><%= t('editing.brand') %></h1>

<%= render 'form', brand: @brand %>

<%= link_to t('links.show'), @brand, class:"btn btn-primary" %> |
<%= link_to t('links.back'), brands_path, class:"btn btn-primary" %>

app/views/brands/index.html.erb
<p style="color: green"><%= notice %></p>

<% if @brands.count > 0 %>

  <h1><%= Brand.model_name.human(count: @brands.count) %></h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= @brands.human_attribute_name(:brand_name) %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @brands.each do |brand| %>
        <tr>
          <td><%= brand.brand_name %></td>
          <td><%= link_to t('links.show'), brand %></td>
          <td><%= link_to t('links.edit'), edit_brand_path(brand) %></td>
          <td><%= link_to t('links.delete'), brand, method: :delete, data: { turbo_method: :delete, turbo_confirm: t('messages.warning', :brand => brand.brand_name) + t('messages.confirm') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>

  <br>

  <P class="font-weight-bold text-danger text-center"> <%= t('empty.brand') %> </P>

  <br>
  
<% end %> 


<br>

<%= link_to t('new.brand'), new_brand_path, class:"btn btn-primary" %>

app/views/brands/new.html.erb
<h1><%= t('new.brand') %></h1>

<%= render 'form', brand: @brand %>

<%= link_to t('links.back'), brands_path, class:"btn btn-primary" %>

app/views/brands/show.html.erb
<p style="color: green"><%= notice %></p>

<form>

  <div class="form-group">
    <%= label_tag nil, @brand.class.human_attribute_name(:brand_name) %>
    <%= text_field_tag nil, @brand.brand_name, class:"form-control", disabled: true %>
  </div>

</form>

<% if @brand.cars.count > 0 %>

  <h4>
    <% if I18n.locale == :en %>
      <p><%= @brand.brand_name %> <%= Car.model_name.human(count: @brand.cars.count)%></p>
    <% elsif I18n.locale.to_s == 'pt-BR' %>
      <p><%= Car.model_name.human(count: @brand.cars.count)%> da <%= @brand.brand_name %></p>
    <% end %>
  </h4>
   
   <%#= Car.model_name.human(count: @brand.cars.count)%> 


  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= @brand.cars.human_attribute_name(:description) %></th>
        <th><%= @brand.cars.human_attribute_name(:year) %></th>
        <th><%= @brand.cars.human_attribute_name(:url_image) %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @brand.cars.each do |car| %>
        <tr>
          <td><%= car.description %></td>
          <td><%= car.year %></td>
          <td> <%= image_tag car_url_image(car), size: "125x80", alt: "#{car.description} image" %> </td>
          <td><%= link_to t('links.show'), car %></td>
          <td><%= link_to t('links.edit'), edit_car_path(car) %></td>
          <td><%= link_to t('links.delete'), car, data: { turbo_method: :delete, turbo_confirm: t('messages.confirm') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>

  <br>

  <P class="font-weight-bold text-danger text-center"> <%= t('empty.car') %> </P>

  <br>
  
<% end %>  

<%= link_to t('links.edit'), edit_brand_path(@brand), class:"btn btn-primary" %> |
<%= link_to t('links.back'), brands_path, class:"btn btn-primary" %>

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <p>
    <strong>Description:</strong>
    <%= car.description %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= car.year %>
  </p>

  <p>
    <strong>Url image:</strong>
    <%= car.url_image %>
  </p>

</div>

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, t('error', count: car.errors.count)) %> <%= t('error_explanation.car', count: car.errors.count) %></h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class:"form-control", placeholder:"Volkswagen Beetle" %>
  </div>

  <div class="form-group">
    <%= form.label :year %>
    <%= form.number_field :year, class:"form-control", placeholder:"1970" %>
  </div>

  <div class="form-group">
    <%= form.label :url_image %>
    <i class="text-muted"><%= t('messages.optional') %></i>
    <%= form.text_field :url_image, class:"form-control", placeholder:"https://i.imgur.com/beetle.jpeg" %>
  </div>
  
  <div class="form-group">
    <%= form.label :brand_id %>
    <%= form.select("brand_id", @brand_options, { include_blank: t('messages.select_box') }, class:"form-control") %>
  </div>

  <div class="actions">
    <%= form.submit nil, class:"btn btn-primary"  %>
  </div>
<% end %>

</br>

app/views/cars/edit.html.erb
<h1><%= t('editing.car') %></h1>

<%= render 'form', car: @car %>

<%= link_to t('links.show'), @car, class:"btn btn-primary"  %> |
<%= link_to t('links.back_to') + " #{@car.brand.brand_name}", @car.brand, class:"btn btn-primary"  %> |
<%= link_to t('links.back_to') + " #{Car.model_name.human(count: :many)}", cars_path, class:"btn btn-primary" %>

app/views/cars/index.html.erb
<p style="color: green"><%= notice %></p>

<% if @cars.count > 0 %>

  <h1><%= Car.model_name.human(count: @cars.count) %></h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= @cars.human_attribute_name(:description) %></th>
        <th><%= @cars.human_attribute_name(:year) %></th>
        <th><%= @cars.human_attribute_name(:url_image) %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @cars.each do |car| %>
        <tr>
          <td><%= car.description %></td>
          <td><%= car.year %></td>
          <td> <%= image_tag car_url_image(car), size: "125x80", alt: "#{car.description} image" %> </td>
          <td><%= link_to t('links.show'), car %></td>
          <td><%= link_to t('links.edit'), edit_car_path(car) %></td>
          <td><%= link_to t('links.delete'), car, data: { turbo_method: :delete, turbo_confirm: t('messages.confirm') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>

  <br>

  <P class="font-weight-bold text-danger text-center"> <%= t('empty.car') %> </P>

  <br>
  
<% end %> 


<br>

<%= link_to t('new.car'), new_car_path, class:"btn btn-primary" %>

app/views/cars/new.html.erb
<h1><%= t('new.car') %></h1>

<%= render 'form', car: @car %>

<%= link_to t('links.back'), cars_path, class:"btn btn-primary" %>

app/views/cars/show.html.erb
<p style="color: green"><%= notice %></p>

<form>

  <div class="form-group">
    <%= label_tag nil, @car.class.human_attribute_name(:description) %>
    <%= text_field_tag nil, @car.description, class:"form-control", disabled: true %>
  </div>

  <div class="form-group">
    <%= label_tag nil, @car.class.human_attribute_name(:year) %>
    <%= text_field_tag nil, @car.year, class:"form-control", disabled: true %>
  </div>

  <% if !@car.url_image.empty? %>

    <div class="form-group">
      <%= label_tag nil, @car.class.human_attribute_name(:url_image) %>
      <%= text_field_tag nil,@car.url_image , class:"form-control", disabled: true %>
    </div>

  <% end %>
  
  <div class="form-group">
    <%= label_tag nil, @car.class.human_attribute_name(:brand) %>
    <%= text_field_tag nil, @car.brand.brand_name , class:"form-control", disabled: true %>
  </div>
  
</form>

<%= link_to t('links.edit'), edit_car_path(@car), class:"btn btn-primary" %> |
<%= link_to t('links.back_to') + " #{@car.brand.brand_name}", @car.brand, class:"btn btn-primary"  %> |
<%= link_to t('links.back_to') + " #{Car.model_name.human(count: :many)}", cars_path, class:"btn btn-primary" %>

app/views/layouts/_locale_links.html.erb
<% if I18n.locale == I18n.default_locale %>
  <li data-turbo-prefetch="false" class="nav-item">
    <%= link_to 'Português', root_path(locale: 'pt-BR'), class:"nav-link text-secondary" %>
  </li>
<% else %>  
  <li data-turbo-prefetch="false" class="nav-item">
    <%= link_to 'English', root_path(locale: 'en'), class:"nav-link text-secondary" %>
  </li>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarCatalogue</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <div class="container-fluid">
      <ul class="nav justify-content-end">
        <%= active_link_to 'Home', root_path %>
        <%= active_link_to "#{Car.model_name.human(count: :many)}", cars_path %>
        <%= active_link_to "#{Brand.model_name.human(count: :many)}", brands_path %>
        <%= render "layouts/locale_links" %>
      </ul>
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/_menu.html.erb
<%= link_to "#{Car.model_name.human(count: :many)}", cars_path, class:"btn btn-primary btn-lg", role:"button" %>
<%= link_to "#{Brand.model_name.human(count: :many)}", brands_path, class:"btn btn-primary btn-lg", role:"button" %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= t('welcome') %></h1>
  <p class="lead"><%= t('messages.welcome').html_safe %></p>
  <hr class="my-4">
  <p><%= t('messages.menu') %></p>
  <%= render "menu" %>
</div>